### ISSUE TITLE
How to combine Grack with Rails?

### ISSUE THREAD

**Issue by Qqwy** [grackorg/grack#6]
I am wondering on how to use Grack in a Rails application. The main problem I seem to be having is to have Grack realize what path it is called from.

I have set, in my `config/routes.rb` file of Rails:

```
get "/grack/(:grack_path)" => GrackApp.action(:index)
```

`controllers/grack_app.rb` contains the following:

```
    class GrackApp < ActionController::Metal

    def index
        config = {
          :root => Rails.root.join("public", "some", "repository", "path").to_s,
          :allow_push => true,
          :allow_pull => true,
          :git_adapter_factory => ->{ Grack::GitAdapter.new }
        }
        puts Rack::Request.new(env).inspect

        Grack::App.new(config).call(env)
    end

end
```

Then, when running `git:clone http://localhost:3000/grack`, I get the following Rack error trace:

```
Started GET "/grack/project-1/info/refs?service=git-upload-pack" for 127.0.0.1 at 2015-10-23 22:20:20 +0200

NoMethodError (undefined method `each' for nil:NilClass):
  rack (1.6.4) lib/rack/etag.rb:65:in `digest_body'
  rack (1.6.4) lib/rack/etag.rb:28:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /home/qqwy/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /home/qqwy/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /home/qqwy/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

What am I doing wrong? How can I configure Grack to use the designated route as its root route?

**Comment by dometto** [comment]
Are you sure you're passing the correct `:root` in the config? The root + the request path (`project-1` in your example) should be a valid git repository.

As for the way you're setting up the Rails routes, that doesn't look ideal, at least if you also want grack to handle uploads. Easiest way is to `mount YourWrapperClass :at 'grack'` (where `YourWrapperClass` is a class that responds to `#call` and sets up and calls a `Grack::App`).

**Comment by dometto** [comment]
@Qqwy, did you manage to solve your problem?

**Comment by Qqwy** [comment]
@dometto: Sorry for my slow reply.

Yes, using `mount YourWrapperClass, at: 'route_name'` works wonderfully. Thank you very much for your help!

**Comment by anthonycorletti** [comment]
Hey! Curious if this is still something that can be used for serving git repos over http for rails? im working on this myself and I'm able to mount my wrapper class, but whenever I try git cloning/pushing any redirect to `/git/teamname/codebasename.git/info/refs` is not found. Does this automatically implement the info/ref calls for us or do we have to implement those ourselves?

**Comment by dometto** [comment]
`grack` should handle that for you as the underlying adapter (the default one using C-git or the alternative one using RJGit) implements the git smart http protocol. I'm not sure from what you're saying whether you're using grack and it's not showing this behavior, or you're using something else at the moment?

**Comment by anthonycorletti** [comment]
Hey thanks! I had something misconfigured with my app. I figured it out and I'll post the fix sometime soon.

**Comment by anthonycorletti** [comment]
Here is where I landed:

```ruby
# lib/grack_git.rb
require "grack/app"
require "grack/git_adapter"

class GrackAuth
  def initialize(app)
    @app = app
  end

  def call(env)
    request = Rack::Request.new(env)

    # basic auth for example
    auth = Rack::Auth::Basic::Request.new(env)

    if valid_git_request?(auth, username, token, request)
      return @app.call(env)
    else
      return unauthorized
    end
  end

  private

  def valid_git_request?(auth, username, token, request)
    # ...
  end

  def unauthorized
    [401, { "Content-Type" => "text/plain", "WWW-Authenticate" => 'Basic realm="Restricted Area"' }, ["Unauthorized"]]
  end
end

class GrackGit
  def self.app
    config = {
      :root => ENV["GIT_HOME"],
      :allow_push => true,
      :allow_pull => true,
      :git_adapter_factory => -> { Grack::GitAdapter.new },
    }

    Rack::Builder.new do
      use GrackAuth
      run Grack::App.new(config)
    end.to_app
  end
end
```

```ruby
# config/initializers/grack_git.rb
ENV["GIT_HOME"] = ENV["GIT_HOME"] ||  "/srv/git"

begin
  FileUtils.mkdir_p(ENV["GIT_HOME"]) unless File.directory?(ENV["GIT_HOME"])
  require Rails.root.join("lib/grack_git")
rescue => e
  puts "Error: #{e} –– are you sure you have the right permissions, in the right environment to create the directory at #{ENV["GIT_HOME"]}?"
end
```

```ruby
# config/routes.rb
Rails.application.routes.draw do
  # errors
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  # ...

  class GitAgentConstraint
    def matches?(request)
      request.headers["User-Agent"].to_s.start_with?("git/")
    end
  end

  # git routes
  constraints(GitAgentConstraint.new) do
    mount GrackGit.app, at: "/"
  end

  # ...
end
```
